name = "dream_cors"
version = "0.1.0"
description = "A Dream Framework plugin for CORS"
licenses = ["MIT"]
repository = { type = "github", user = "intoxii", repo = "dream_cors" }

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
dream = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleam_otp = ">= 1.2.0 and < 2.0.0"